version: '3'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - mysql
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.0.28
    ports:
      - "3306"
    #build:
    #  context: .
    #  dockerfile: mysql_Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "password"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
