version: '3'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links:
      - mongodb
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
